### PR TITLE
chunk renderer

### PR DESCRIPTION
**Pull request by Ryboster**

### CODE REVIEW

**Review by vileider — CHANGES_REQUESTED** [review]
Line 132 fix file name

**Comment by vileider** [comment]
Line 97 and 98 Change to capital  "L" and "W"

**Comment by vileider** [comment]
after running chunk render i get error `703
Traceback (most recent call last):
  File ".\chunk_renderer.py", line 141, in <module>
    render.create_png(chunk.chunk_data, chunk.name)
  File ".\chunk_renderer.py", line 121, in create_png
    result_image.save(f'images/{name}.png')
  File "C:\Users\andrew\AppData\Local\Programs\Python\Python38\lib\site-packages\PIL\Image.py", line 2209, in save
    fp = builtins.open(filename, "w+b")
FileNotFoundError: [Errno 2] No such file or directory: 'images/0,0.png'
`

**Comment by vileider** [comment]
line 16, 49, 53, 58 variables not in use

**Comment by Ryboster** [comment]
> after running chunk render i get error `703 Traceback (most recent call last): File ".\chunk_renderer.py", line 141, in <module> render.create_png(chunk.chunk_data, chunk.name) File ".\chunk_renderer.py", line 121, in create_png result_image.save(f'images/{name}.png') File "C:\Users\andrew\AppData\Local\Programs\Python\Python38\lib\site-packages\PIL\Image.py", line 2209, in save fp = builtins.open(filename, "w+b") FileNotFoundError: [Errno 2] No such file or directory: 'images/0,0.png' `

The script attempted to create an image file in the /images/ folder, but the folder was not found. I'll sort out the structure

**Comment by Ryboster** [comment]
> Line 97 and 98 Change to capital "L" and "W"

changed.

**Comment by Ryboster** [comment]
> Line 132 fix file name

changed

**Comment by Ryboster** [comment]
> line 16, 49, 53, 58 variables not in use

those variables are now removed

**Comment by Ryboster** [comment]
Most of the files staged are pre-rendered pictures of the alpha_map.csv file. The map is rendered vertically, and here is a 2d representation of the expected sequence:
0,0 1,0 2,0
0,1 1,1 2,1
0,2 1,2 2,2

Before running make sure /images/ folder is empty and exists.

**Review by vileider — APPROVED** [review]
It is working, creates .png images with the coordinates as file name. 
This will need some small fixes in the future like:
- line 52 unused variables 
- readme file with information about used libraries in the project(numpy, pillow, pygame)
- script should erase files from images folder or validate it
- I think script needs to be optimize - takes to much time to create

Above issues are minor and do not effect on the whole project
Good Job Gracjan this was not the easy task.

**Pull request merged**
