### PR TITLE
Statistics class for characters

### PR DESCRIPTION
**Pull request by Ryboster**
Created a statistics class to be inherited by character classes.

### CODE REVIEW

**Comment by vileider** [comment]
Why there is no min health or mana or gold?

**Review by vileider — COMMENTED** [review]
as I mentioned why no min health and mana?

**Comment by Ryboster** [comment]
@vileider Min health and mana are not needed. Min mana is going to be handled by skill mana requirements in use_spell function that we don't yet have. As for hp, that's going to be checked by the take_damage() function; If player takes damage and their hp is equal to or below 0, they trigger the die() function that we'll create later.

As for gold, that seems redundant, too, since it can be handled from different places.

**Comment by Ryboster** [comment]
@vileider you can already see some rudimentary handling of these minimum and maximum values here:
image

**Review by vileider — COMMENTED** [review]
looks ok

**Review by vileider — APPROVED** [review]
looks ok

**Comment by Ryboster** [comment]
Thanks. Merging

**Pull request merged**
