### PR TITLE
T 60

### PR DESCRIPTION
**Pull request by Ryboster**
### Alpha build utilizing the following features:
* Box camera
* Center target camera
* Zooming in and out
* Toggled meshing (F1 to display tiles on top of chunk images)
* Offset
* Layering
* Collision based rendering
* Free movement in all 4 directions
* Acceleration and deceleration

### CODE REVIEW

**Comment by Ryboster** [comment]
Most of the staged files are chunk images. In case of a conflict with T-51, I'll remove them.

The script necessitated alteration of multiple module files and introduction of a temporary chunk loading script. Most changes were made to camera_group. Review them with care.

It is intended to be run from parent directory (/game_project/).

The script ran well on my machine, but there might be conflicts with windows due to file paths

**Comment by Ryboster** [comment]
ignore cache files

**Review by vileider — APPROVED** [review]
it takes 5s to run it on my i712700k 32GB RAM and 5600 nvme. Definitely  it needs refactor and to be optimized. Once I open it it works.

**Comment by Ryboster** [comment]
One of the reason it might be taking that long to start is that it reads the whole CSV on startup. That usually takes a while

**Pull request merged**
